language: python
python:
  - "2.7"
  - "3.6"

branches:
  only:
  - master

env:
  global:
      - PYTHONPATH=.

install:
  - "pip install -r requirements.txt"

# command to run tests
script:
  - "./tests/travis/run.sh"
